api:
  - changed-files:
      - any-glob-to-any-file: "jarble-api-main/**"
frontend:
  - changed-files:
      - any-glob-to-any-file: "Jarble-mvp/**"
infrastructure:
  - changed-files:
      - any-glob-to-any-file: "infrastructure/**"
shared:
  - changed-files:
      - any-glob-to-any-file: "shared/**"
ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
runtimes:
  - changed-files:
      - any-glob-to-any-file: "runtimes/**"
