/**
 * Flow Delegation Service
 *
 * Generates delegation tools from flow edges and executes delegations
 * by calling deployment chat endpoints (same as tamboAgent.ts).
 *
 * Core responsibilities:
 *   1. Build delegation "tools" from outgoing "delegates" edges
 *   2. Augment a bot's system prompt with role, goal, and delegation instructions
 *   3. Execute a delegation by sending a task to a target deployment's pod
 */

import { db, tables } from "../db/index.js";
import { eq, and, or, inArray } from "drizzle-orm";
import { createModuleLogger } from "../utils/logger.js";
import { emitOrchestrationStart, emitOrchestrationEnd } from "../utils/agentCallEvents.js";
import { nanoid } from "nanoid";
import type { FlowNode, FlowEdge } from "./flowEngine.js";
import type { DeploymentCapabilities } from "./deploymentCapabilities.js";

const log = createModuleLogger("flow-delegation");

// ── Types ────────────────────────────────────────────────────────────────────

export interface DelegationTool {
  name: string;                   // "delegate_to_cto"
  description: string;            // Includes role and goal of target
  targetNodeId: string;
  targetDeploymentId: string;
  contextScope: "task" | "summary" | "full";
}

export interface DelegationResult {
  response: string;
  creditsUsed: number;
  durationMs: number;
  targetNodeId: string;
  targetDeploymentId: string;
  /** UI blocks generated by the delegate bot (charts, tables, sandboxes, etc.) */
  uiBlocks?: any[];
  /** Component definitions registered by the delegate */
  componentDefs?: any[];
  /** Suggestions from the delegate */
  suggestions?: string[];
}

// ── Constants ────────────────────────────────────────────────────────────────

/** Maximum delegation chain depth to prevent infinite loops */
const MAX_DELEGATION_DEPTH = 5;

/** Timeout for a single delegation call (ms) */
const DELEGATION_TIMEOUT_MS = 90_000;

// ── Build delegation tools ───────────────────────────────────────────────────

/**
 * Build delegation tools for a node based on its outgoing "delegates" edges.
 *
 * Only considers edges where type === "delegates" (or unset, defaulting to
 * "delegates" for backward compatibility). Target nodes must have a valid
 * deploymentId.
 */
export function buildDelegationTools(
  node: FlowNode,
  nodes: FlowNode[],
  edges: FlowEdge[],
  capabilitiesMap?: Map<string, DeploymentCapabilities>,
): DelegationTool[] {
  if (node.canDelegate === false) return [];

  // Find all outgoing "delegates" edges from this node
  const delegateEdges = edges.filter(
    (e) => e.source === node.id && (e.type === "delegates" || !e.type),
  );

  const tools: DelegationTool[] = [];

  for (const edge of delegateEdges) {
    const targetNode = nodes.find((n) => n.id === edge.target);
    if (!targetNode || !targetNode.deploymentId) continue;

    // Build a safe function name from the target's role/label/id
    const safeName = (targetNode.role || targetNode.label || targetNode.id)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40);

    const goalStr = targetNode.goal ? ` Goal: ${targetNode.goal}` : "";
    const caps = capabilitiesMap?.get(targetNode.deploymentId);
    let capsStr = "";
    if (caps) {
      capsStr = ` ${caps.llmSummary}`;
    }

    tools.push({
      name: `delegate_to_${safeName}`,
      description: `Delegate a task to ${targetNode.role || targetNode.label}.${goalStr}${capsStr}`,
      targetNodeId: targetNode.id,
      targetDeploymentId: targetNode.deploymentId,
      contextScope: edge.contextScope || targetNode.contextScope || "task",
    });
  }

  return tools;
}

// ── Build augmented system prompt ────────────────────────────────────────────

/**
 * Build the system prompt augmentation for a bot operating within a flow.
 * Injects role, goal, and delegation instructions, layered on top of the
 * deployment's base system prompt.
 */
export function buildFlowSystemPrompt(
  node: FlowNode,
  delegationTools: DelegationTool[],
  basePrompt: string,
): string {
  const parts = [basePrompt];

  if (node.role || node.goal) {
    parts.push("\n\n## Your Role in This Team");
    if (node.role) parts.push(`You are the **${node.role}**.`);
    if (node.goal) parts.push(`Your goal: ${node.goal}`);
  }

  if (delegationTools.length > 0 && node.canDelegate !== false) {
    // Build the slug roster (the "to" field of the fenced block uses the
    // bare slug — without the "delegate_to_" prefix — so the LLM never has
    // to type a tool prefix it might mangle).
    const memberLines = delegationTools
      .map((tool) => {
        const slug = tool.name.replace(/^delegate_to_/, "");
        return `- **${slug}**: ${tool.description}`;
      })
      .join("\n");

    // Pick a sample slug for the one-shot example.
    const sampleSlug =
      delegationTools[0].name.replace(/^delegate_to_/, "") || "specialist";

    parts.push("\n\n## Team Members You Can Delegate To");
    parts.push(
      "You are part of a team. Each member below is a full agent that may have " +
      "its own internal specialists. When a task matches a member's capabilities, " +
      "delegate to them instead of attempting it yourself.",
    );
    parts.push("\n" + memberLines);

    parts.push(
      "\n\n## How to Delegate — REQUIRED FORMAT\n" +
      "To delegate, emit a fenced code block tagged `jarble_delegate` containing a " +
      "JSON object. The block is the ONLY way to delegate — no other format works. " +
      "There is no per-member tool (like `delegate_to_<name>`); the single canonical " +
      "delegation tool is the `jarble_delegate` fenced block, and the `to` field picks " +
      "the target by bare slug.\n" +
      "\nFields:\n" +
      "- `to`      — REQUIRED string, the bare slug of the team member (from the list above — NOT prefixed with `delegate_to_`)\n" +
      "- `task`    — REQUIRED string, the task to delegate\n" +
      "- `context` — OPTIONAL string, additional context to pass with the task\n" +
      "\nExample (one-shot):\n" +
      "```jarble_delegate\n" +
      `{ "to": "${sampleSlug}", "task": "Describe primary colors", "context": "" }\n` +
      "```\n" +
      "\n## When You MUST Delegate — Strong Triggers\n" +
      "If the user's message contains ANY of the following, you MUST emit a " +
      "`jarble_delegate` block instead of answering yourself, even if you are capable " +
      "of answering directly. The user is explicitly invoking the team structure — " +
      "answering yourself defeats the purpose of having teammates.\n" +
      "\n" +
      "- The user names a team member by slug, role, or label (e.g. \"ask " +
      `${sampleSlug}\", \"have ${sampleSlug} do X\", \"what does ${sampleSlug} say\")\n` +
      "- The user references your team in the abstract (e.g. \"your specialist\", " +
      "\"your team\", \"your researcher\", \"your expert\", \"have one of your bots\", " +
      "\"a team member\")\n" +
      "- The user uses delegation verbs targeted at your team (\"delegate this\", " +
      "\"hand this off to\", \"pass this to\", \"forward this to\")\n" +
      "\n" +
      "Choose the team member whose role best matches the request. When in doubt " +
      "between two members, pick the one whose listed description most directly " +
      "covers the user's task. Do NOT delegate every casual question — only when the " +
      "user references the team OR when the request clearly matches a member's listed " +
      "specialty better than your own coordinator role.\n" +
      "\n## Hard Rules — READ CAREFULLY\n" +
      "1. Emit ONLY the fenced `jarble_delegate` block. Do NOT describe what you are " +
      "doing in prose first. The user does not see the block — they see only the final " +
      "synthesized response after the delegation completes.\n" +
      "2. Never claim you delegated unless you actually emitted a `jarble_delegate` block " +
      "in this same response. Saying \"I've delegated this\" without the block is a " +
      "silent failure that leaves the user waiting forever.\n" +
      "3. To broadcast to multiple members, emit multiple `jarble_delegate` blocks in " +
      "the same response.\n" +
      "4. After delegations complete, you will be called again with their results " +
      "to integrate into a final synthesis. The full reply from each member will be " +
      "included verbatim — do NOT claim it was truncated.\n" +
      "5. If you can handle the request yourself AND the user has not invoked any of " +
      "the strong triggers above, respond directly without emitting any " +
      "`jarble_delegate` block.",
    );
  }

  return parts.join("\n");
}

// ── Parse delegation tool calls from bot response ────────────────────────────

interface ParsedDelegationCall {
  toolName: string;
  task: string;
  context?: string;
}

/**
 * Parse delegation tool call blocks from bot response text.
 *
 * Two formats are supported:
 *
 *  1. NEW (preferred) — fenced ```jarble_delegate``` block with shape:
 *       { "to": "<slug>", "task": "...", "context": "..." }
 *     The `to` slug is converted to a `delegate_to_<slug>` toolName so the
 *     downstream lookup against DelegationTool.name still works.
 *
 *  2. LEGACY (DEPRECATED, will be removed in a follow-up PR) — fenced
 *     ```json``` block with shape:
 *       { "tool": "delegate_to_<slug>", "task": "...", "context": "..." }
 *
 * Returns all found delegation calls (there may be multiple for broadcast).
 * Both formats may appear in the same response during the rollout window —
 * we accept both and de-duplicate by (toolName, task).
 */
export function parseDelegationCalls(text: string): ParsedDelegationCall[] {
  const calls: ParsedDelegationCall[] = [];

  // ── NEW FORMAT: ```jarble_delegate``` blocks ──────────────────────────
  // Spec: code fence with language tag `jarble_delegate`. Body is a JSON
  // object with "to" (REQUIRED), "task" (REQUIRED), "context" (OPTIONAL).
  const delegateBlockRegex = /```jarble_delegate\s*\n([\s\S]*?)```/g;
  let dm: RegExpExecArray | null;
  while ((dm = delegateBlockRegex.exec(text)) !== null) {
    try {
      const parsed = JSON.parse(dm[1].trim());
      if (
        parsed &&
        typeof parsed === "object" &&
        parsed.to &&
        typeof parsed.to === "string" &&
        parsed.task &&
        typeof parsed.task === "string"
      ) {
        // Strip any accidental "delegate_to_" prefix the LLM may add by
        // mistake (the spec says "to" should be the bare slug).
        const slug = parsed.to.replace(/^delegate_to_/, "");
        calls.push({
          toolName: `delegate_to_${slug}`,
          task: parsed.task,
          context:
            typeof parsed.context === "string" && parsed.context.length > 0
              ? parsed.context
              : undefined,
        });
      }
    } catch {
      // Not valid JSON in the jarble_delegate block — skip silently.
      // The skipReason heuristic in flowChat.ts will surface the failure.
    }
  }

  // ── DEPRECATED: legacy delegation format, will be removed in a follow-up PR ──
  // Backward compat for bots still on the old soul.md prompt that says to
  // emit ```json { "tool": "delegate_to_..." }```. New prompt no longer
  // teaches this format. Remove once all running pods have re-synced.
  const jsonBlockRegex = /```json\s*\n([\s\S]*?)```/g;
  let lm: RegExpExecArray | null;
  while ((lm = jsonBlockRegex.exec(text)) !== null) {
    try {
      const parsed = JSON.parse(lm[1].trim());
      if (
        parsed &&
        typeof parsed === "object" &&
        parsed.tool &&
        typeof parsed.tool === "string" &&
        parsed.tool.startsWith("delegate_to_") &&
        parsed.task &&
        typeof parsed.task === "string"
      ) {
        calls.push({
          toolName: parsed.tool,
          task: parsed.task,
          context:
            typeof parsed.context === "string" && parsed.context.length > 0
              ? parsed.context
              : undefined,
        });
      }
    } catch {
      // Not valid JSON or not a delegation call - skip
    }
  }

  // De-dupe by (toolName, task) so a bot that emits BOTH a jarble_delegate
  // block AND the legacy json block for the same delegation only triggers once.
  const seen = new Set<string>();
  const deduped: ParsedDelegationCall[] = [];
  for (const c of calls) {
    const key = `${c.toolName}::${c.task}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(c);
  }

  return deduped;
}

// ── Execute delegation ───────────────────────────────────────────────────────

/**
 * Execute a delegation - send a task to a target deployment and get the response.
 *
 * Uses the same chat pathway as tamboAgent (exec into pod via K8s API).
 * This is the non-streaming variant: the delegation completes and the full
 * response text is returned.
 */
export async function executeDelegation(params: {
  targetDeploymentId: string;
  targetNodeId: string;
  task: string;
  context?: string;
  contextScope: "task" | "summary" | "full";
  conversationHistory?: Array<{ role: string; content: string }>;
  sessionId?: string;
  depth?: number;
  /** Source deployment ID - used to scope orchestration events to the right SSE stream */
  sourceDeploymentId?: string;
  /** Tool name for orchestration event (e.g. "delegate_to_cto") */
  toolName?: string;
  /** User ID for ownership verification — prevents IDOR on delegation targets */
  userId?: string;
  /** Parent agent_calls row id. If set, this delegation becomes a child of
   *  that call in the fractal tree (JAR-50 agent_calls writer). */
  parentCallId?: string | null;
  /** Parent OTel span id (usually matches parent call's span_id). */
  parentSpanId?: string | null;
  /** Trace id for the root chat turn. Propagates unchanged through every
   *  recursive delegation so the whole fractal tree stitches to one trace. */
  traceId?: string | null;
  /** Org scope for audit rollups. */
  orgId?: string | null;
}): Promise<DelegationResult> {
  const depth = params.depth ?? 0;
  if (depth >= MAX_DELEGATION_DEPTH) {
    throw new Error(
      `Delegation depth limit reached (${MAX_DELEGATION_DEPTH}). ` +
      "Possible circular delegation or overly deep chain.",
    );
  }

  const startTime = Date.now();

  // Look up the target deployment with ownership verification
  // (check both personal ownership and org membership)
  let whereConditions;
  if (params.userId) {
    const memberships = await db.query.orgMembers.findMany({
      where: eq(tables.orgMembers.userId, params.userId),
      columns: { orgId: true },
    });
    const orgIds = memberships.map((m: any) => m.orgId);

    const ownershipFilter = orgIds.length > 0
      ? or(eq(tables.deployments.userId, params.userId), inArray(tables.deployments.orgId, orgIds))
      : eq(tables.deployments.userId, params.userId);

    whereConditions = and(eq(tables.deployments.id, params.targetDeploymentId), ownershipFilter);
  } else {
    whereConditions = eq(tables.deployments.id, params.targetDeploymentId);
  }

  const deployment = await db.query.deployments.findFirst({
    where: whereConditions,
  });

  if (!deployment) {
    throw new Error(`Delegation target not found: ${params.targetDeploymentId}`);
  }

  if (deployment.status !== "running") {
    throw new Error(
      `Delegation target "${deployment.name}" is not running (status: ${deployment.status})`,
    );
  }

  // Build the message based on context scope
  let message = params.task;
  if (params.contextScope === "summary" && params.context) {
    message = `Context: ${params.context}\n\nTask: ${params.task}`;
  } else if (params.contextScope === "full" && params.conversationHistory) {
    const history = params.conversationHistory
      .slice(-20) // Cap history to avoid massive payloads
      .map((m) => `${m.role}: ${m.content}`)
      .join("\n");
    message = `Conversation so far:\n${history}\n\nTask: ${params.task}`;
  }

  // Find the pod for this deployment and exec into it
  const { chatViaExec } = await import("./openclawGateway.js");
  const { findPodForDeployment } = await import("../k8s/index.js");

  const podName = await findPodForDeployment(params.targetDeploymentId);
  if (!podName) {
    throw new Error(
      `No running pod found for deployment "${deployment.name}" (${params.targetDeploymentId})`,
    );
  }

  const sessionId =
    params.sessionId || `flow-delegation-${params.targetDeploymentId}-${Date.now()}`;

  log.info(
    {
      targetDeploymentId: params.targetDeploymentId,
      targetNodeId: params.targetNodeId,
      depth,
      messageLen: message.length,
    },
    "Executing delegation",
  );

  // ── JAR-50: record agent_calls row for the delegation hop ─────────────────
  // Fire-and-forget: the writer catches its own errors so audit failures
  // can never break the delegation path.
  const { startAgentCall, finishAgentCall } = await import("./agentCallsWriter.js");
  const agentCallHandle = await startAgentCall({
    kind: "delegation",
    skillName: params.toolName || `delegate_to_${params.targetNodeId}`,
    callerDeploymentId: params.sourceDeploymentId || null,
    calleeDeploymentId: params.targetDeploymentId,
    parentCallId: params.parentCallId ?? null,
    parentSpanId: params.parentSpanId ?? null,
    traceId: params.traceId ?? null,
    depth,
    userId: params.userId ?? null,
    orgId: params.orgId ?? null,
    sessionId,
    podName,
    spanName: "jarble.delegation.hop",
    requestBody: { task: params.task, contextScope: params.contextScope },
    attributes: {
      targetNodeId: params.targetNodeId,
      contextScope: params.contextScope,
      messageLen: message.length,
    },
  });

  // ── Emit orchestration:step:start event ──────────────────────────────────
  const stepId = `delegation-${nanoid(8)}`;
  const orchestrationDeploymentId = params.sourceDeploymentId || params.targetDeploymentId;
  const orchestrationToolName = params.toolName || `delegate_to_${params.targetNodeId}`;

  try {
    emitOrchestrationStart({
      deploymentId: orchestrationDeploymentId,
      stepId,
      agentType: "delegation",
      agentName: deployment.name || params.targetNodeId,
      toolName: orchestrationToolName,
      task: params.task.slice(0, 200),
      targetDeploymentId: params.targetDeploymentId,
    });
  } catch {
    // Non-fatal - orchestration events are nice-to-have
  }

  // Create an AbortController with timeout
  const abortController = new AbortController();
  const timeout = setTimeout(
    () => abortController.abort(),
    DELEGATION_TIMEOUT_MS,
  );

  try {
    const result = await chatViaExec(
      podName,
      sessionId,
      message,
      undefined, // no onDelta for delegations (not streaming to user)
      undefined, // no canvas image
      abortController.signal,
    );

    const durationMs = Date.now() - startTime;

    log.info(
      {
        targetDeploymentId: params.targetDeploymentId,
        targetNodeId: params.targetNodeId,
        durationMs,
        responseLen: result.text.length,
      },
      "Delegation completed",
    );

    // ── Emit orchestration:step:end event ──────────────────────────────────
    try {
      emitOrchestrationEnd({
        deploymentId: orchestrationDeploymentId,
        stepId,
        agentType: "delegation",
        agentName: deployment.name || params.targetNodeId,
        toolName: orchestrationToolName,
        targetDeploymentId: params.targetDeploymentId,
        success: true,
        durationMs,
        resultPreview: (result.text || "").slice(0, 200),
      });
    } catch {
      // Non-fatal
    }

    // ── JAR-50: finish the agent_calls row as completed ───────────────────
    await finishAgentCall({
      call: agentCallHandle,
      status: "completed",
      responseBody: result.text || "",
      creditsCharged: 1,
      attributes: {
        responseLen: (result.text || "").length,
        uiBlocks: result.uiBlocks?.length || 0,
        componentDefs: result.componentDefs?.length || 0,
      },
    });

    return {
      response: result.text || "",
      creditsUsed: 1, // 1 credit per delegation call
      durationMs,
      targetNodeId: params.targetNodeId,
      targetDeploymentId: params.targetDeploymentId,
      uiBlocks: result.uiBlocks?.length ? result.uiBlocks : undefined,
      componentDefs: result.componentDefs?.length ? result.componentDefs : undefined,
      suggestions: result.suggestions?.length ? result.suggestions : undefined,
    };
  } catch (err) {
    const durationMs = Date.now() - startTime;
    // ── Emit orchestration:step:end with failure ───────────────────────────
    try {
      emitOrchestrationEnd({
        deploymentId: orchestrationDeploymentId,
        stepId,
        agentType: "delegation",
        agentName: deployment.name || params.targetNodeId,
        toolName: orchestrationToolName,
        targetDeploymentId: params.targetDeploymentId,
        success: false,
        durationMs,
        error: err instanceof Error ? err.message : String(err),
      });
    } catch {
      // Non-fatal
    }
    // ── JAR-50: finish the agent_calls row as failed ──────────────────────
    await finishAgentCall({
      call: agentCallHandle,
      status: "failed",
      errorMessage: err instanceof Error ? err.message : String(err),
      attributes: { errorKind: err instanceof Error ? err.name : "unknown" },
    });
    throw err;
  } finally {
    clearTimeout(timeout);
  }
}
