/**
 * Flow Delegation Service
 *
 * Generates delegation tools from flow edges and executes delegations
 * by calling deployment chat endpoints (same as tamboAgent.ts).
 *
 * Core responsibilities:
 *   1. Build delegation "tools" from outgoing "delegates" edges
 *   2. Augment a bot's system prompt with role, goal, and delegation instructions
 *   3. Execute a delegation by sending a task to a target deployment's pod
 */

import { db, tables, dbDate } from "../db/index.js";
import { eq, and, or, inArray } from "drizzle-orm";
import { createModuleLogger } from "../utils/logger.js";
import { emitOrchestrationStart, emitOrchestrationEnd } from "../utils/agentCallEvents.js";
import { nanoid } from "nanoid";
import type { FlowNode, FlowEdge } from "./flowEngine.js";
import type { DeploymentCapabilities } from "./deploymentCapabilities.js";

const log = createModuleLogger("flow-delegation");

// ── Types ────────────────────────────────────────────────────────────────────

export interface DelegationTool {
  name: string;                   // "delegate_to_cto"
  description: string;            // Includes role and goal of target
  targetNodeId: string;
  targetDeploymentId: string;
  contextScope: "task" | "summary" | "full";
}

export interface DelegationResult {
  response: string;
  creditsUsed: number;
  durationMs: number;
  targetNodeId: string;
  targetDeploymentId: string;
  /** UI blocks generated by the delegate bot (charts, tables, sandboxes, etc.) */
  uiBlocks?: any[];
  /** Component definitions registered by the delegate */
  componentDefs?: any[];
  /** Suggestions from the delegate */
  suggestions?: string[];
  /** agent_calls.id row for this delegation — anchor for the parent_call_id tree */
  callId?: string;
  /** Delegation depth this call ran at (1 = first hop from entry bot) */
  depth?: number;
  /** Recursively collected child delegations this call made */
  children?: DelegationResult[];
}

// ── Constants ────────────────────────────────────────────────────────────────

/**
 * Maximum delegation chain depth to prevent infinite recursion.
 *
 * Depth semantics:
 *   0  → user → entry bot (no delegation row; not persisted)
 *   1  → entry bot → specialist   (first delegation hop)
 *   2  → specialist → sub-specialist
 *   ...
 *
 * A call is rejected when `depth > MAX_DELEGATION_DEPTH`. With the default of
 * 4, the chain can go 4 levels deep (depths 1..4).
 *
 * Override via env var `JARBLE_MAX_DELEGATION_DEPTH` (must be a positive int).
 */
const MAX_DELEGATION_DEPTH = (() => {
  const raw = process.env.JARBLE_MAX_DELEGATION_DEPTH;
  const n = raw ? Number(raw) : NaN;
  if (Number.isFinite(n) && n > 0 && n < 20) return Math.floor(n);
  return 4;
})();

export function getMaxDelegationDepth(): number {
  return MAX_DELEGATION_DEPTH;
}

/** Timeout for a single delegation call (ms) */
const DELEGATION_TIMEOUT_MS = 90_000;

// ── Custom errors ────────────────────────────────────────────────────────────

export class DelegationDepthExceededError extends Error {
  public readonly depth: number;
  public readonly maxDepth: number;
  constructor(depth: number) {
    super(
      `Delegation depth limit reached (depth=${depth} > max=${MAX_DELEGATION_DEPTH}). ` +
        "Increase JARBLE_MAX_DELEGATION_DEPTH if deeper chains are intended.",
    );
    this.name = "DelegationDepthExceededError";
    this.depth = depth;
    this.maxDepth = MAX_DELEGATION_DEPTH;
  }
}

export class DelegationCycleError extends Error {
  public readonly chain: string[];
  public readonly target: string;
  constructor(chain: string[], target: string) {
    super(
      `Delegation cycle detected: ${chain.join(" → ")} → ${target}. ` +
        "A bot cannot delegate back to an ancestor already in the current call chain.",
    );
    this.name = "DelegationCycleError";
    this.chain = chain;
    this.target = target;
  }
}

// ── Build delegation tools ───────────────────────────────────────────────────

/**
 * Build delegation tools for a node based on its outgoing "delegates" edges.
 *
 * Only considers edges where type === "delegates" (or unset, defaulting to
 * "delegates" for backward compatibility). Target nodes must have a valid
 * deploymentId.
 */
export function buildDelegationTools(
  node: FlowNode,
  nodes: FlowNode[],
  edges: FlowEdge[],
  capabilitiesMap?: Map<string, DeploymentCapabilities>,
): DelegationTool[] {
  if (node.canDelegate === false) return [];

  // Find all outgoing "delegates" edges from this node
  const delegateEdges = edges.filter(
    (e) => e.source === node.id && (e.type === "delegates" || !e.type),
  );

  const tools: DelegationTool[] = [];

  for (const edge of delegateEdges) {
    const targetNode = nodes.find((n) => n.id === edge.target);
    if (!targetNode || !targetNode.deploymentId) continue;

    // Build a safe function name from the target's role/label/id
    const safeName = (targetNode.role || targetNode.label || targetNode.id)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40);

    const goalStr = targetNode.goal ? ` Goal: ${targetNode.goal}` : "";
    const caps = capabilitiesMap?.get(targetNode.deploymentId);
    let capsStr = "";
    if (caps) {
      capsStr = ` ${caps.llmSummary}`;
    }

    tools.push({
      name: `delegate_to_${safeName}`,
      description: `Delegate a task to ${targetNode.role || targetNode.label}.${goalStr}${capsStr}`,
      targetNodeId: targetNode.id,
      targetDeploymentId: targetNode.deploymentId,
      contextScope: edge.contextScope || targetNode.contextScope || "task",
    });
  }

  return tools;
}

// ── Build augmented system prompt ────────────────────────────────────────────

/**
 * Build the system prompt augmentation for a bot operating within a flow.
 * Injects role, goal, and delegation instructions, layered on top of the
 * deployment's base system prompt.
 */
export function buildFlowSystemPrompt(
  node: FlowNode,
  delegationTools: DelegationTool[],
  basePrompt: string,
): string {
  const parts = [basePrompt];

  if (node.role || node.goal) {
    parts.push("\n\n## Your Role in This Team");
    if (node.role) parts.push(`You are the **${node.role}**.`);
    if (node.goal) parts.push(`Your goal: ${node.goal}`);
  }

  if (delegationTools.length > 0 && node.canDelegate !== false) {
    // Build the slug roster (the "to" field of the fenced block uses the
    // bare slug — without the "delegate_to_" prefix — so the LLM never has
    // to type a tool prefix it might mangle).
    const memberLines = delegationTools
      .map((tool) => {
        const slug = tool.name.replace(/^delegate_to_/, "");
        return `- **${slug}**: ${tool.description}`;
      })
      .join("\n");

    // Pick a sample slug for the one-shot example.
    const sampleSlug =
      delegationTools[0].name.replace(/^delegate_to_/, "") || "specialist";

    parts.push("\n\n## Team Members You Can Delegate To");
    parts.push(
      "You are part of a team. Each member below is a full agent that may have " +
      "its own internal specialists. When a task matches a member's capabilities, " +
      "delegate to them instead of attempting it yourself.",
    );
    parts.push("\n" + memberLines);

    parts.push(
      "\n\n## How to Delegate — REQUIRED FORMAT\n" +
      "To delegate, emit a fenced code block tagged `jarble_delegate` containing a " +
      "JSON object. The block is the ONLY way to delegate — no other format works. " +
      "There is no per-member tool (like `delegate_to_<name>`); the single canonical " +
      "delegation tool is the `jarble_delegate` fenced block, and the `to` field picks " +
      "the target by bare slug.\n" +
      "\nFields:\n" +
      "- `to`      — REQUIRED string, the bare slug of the team member (from the list above — NOT prefixed with `delegate_to_`)\n" +
      "- `task`    — REQUIRED string, the task to delegate\n" +
      "- `context` — OPTIONAL string, additional context to pass with the task\n" +
      "\nExample (one-shot):\n" +
      "```jarble_delegate\n" +
      `{ "to": "${sampleSlug}", "task": "Describe primary colors", "context": "" }\n` +
      "```\n" +
      "\n## When You MUST Delegate — Strong Triggers\n" +
      "If the user's message contains ANY of the following, you MUST emit a " +
      "`jarble_delegate` block instead of answering yourself, even if you are capable " +
      "of answering directly. The user is explicitly invoking the team structure — " +
      "answering yourself defeats the purpose of having teammates.\n" +
      "\n" +
      "- The user names a team member by slug, role, or label (e.g. \"ask " +
      `${sampleSlug}\", \"have ${sampleSlug} do X\", \"what does ${sampleSlug} say\")\n` +
      "- The user references your team in the abstract (e.g. \"your specialist\", " +
      "\"your team\", \"your researcher\", \"your expert\", \"have one of your bots\", " +
      "\"a team member\")\n" +
      "- The user uses delegation verbs targeted at your team (\"delegate this\", " +
      "\"hand this off to\", \"pass this to\", \"forward this to\")\n" +
      "\n" +
      "Choose the team member whose role best matches the request. When in doubt " +
      "between two members, pick the one whose listed description most directly " +
      "covers the user's task. Do NOT delegate every casual question — only when the " +
      "user references the team OR when the request clearly matches a member's listed " +
      "specialty better than your own coordinator role.\n" +
      "\n## Hard Rules — READ CAREFULLY\n" +
      "1. Emit ONLY the fenced `jarble_delegate` block. Do NOT describe what you are " +
      "doing in prose first. The user does not see the block — they see only the final " +
      "synthesized response after the delegation completes.\n" +
      "2. Never claim you delegated unless you actually emitted a `jarble_delegate` block " +
      "in this same response. Saying \"I've delegated this\" without the block is a " +
      "silent failure that leaves the user waiting forever.\n" +
      "3. To broadcast to multiple members, emit multiple `jarble_delegate` blocks in " +
      "the same response.\n" +
      "4. After delegations complete, you will be called again with their results " +
      "to integrate into a final synthesis. The full reply from each member will be " +
      "included verbatim — do NOT claim it was truncated.\n" +
      "5. If you can handle the request yourself AND the user has not invoked any of " +
      "the strong triggers above, respond directly without emitting any " +
      "`jarble_delegate` block.",
    );
  }

  return parts.join("\n");
}

// ── Parse delegation tool calls from bot response ────────────────────────────

export interface ParsedDelegationCall {
  toolName: string;
  task: string;
  context?: string;
}

/**
 * Parse delegation tool call blocks from bot response text.
 *
 * Two formats are supported:
 *
 *  1. NEW (preferred) — fenced ```jarble_delegate``` block with shape:
 *       { "to": "<slug>", "task": "...", "context": "..." }
 *     The `to` slug is converted to a `delegate_to_<slug>` toolName so the
 *     downstream lookup against DelegationTool.name still works.
 *
 *  2. LEGACY (DEPRECATED, will be removed in a follow-up PR) — fenced
 *     ```json``` block with shape:
 *       { "tool": "delegate_to_<slug>", "task": "...", "context": "..." }
 *
 * Returns all found delegation calls (there may be multiple for broadcast).
 * Both formats may appear in the same response during the rollout window —
 * we accept both and de-duplicate by (toolName, task).
 */
export function parseDelegationCalls(text: string): ParsedDelegationCall[] {
  const calls: ParsedDelegationCall[] = [];

  // ── NEW FORMAT: ```jarble_delegate``` blocks ──────────────────────────
  // Spec: code fence with language tag `jarble_delegate`. Body is a JSON
  // object with "to" (REQUIRED), "task" (REQUIRED), "context" (OPTIONAL).
  const delegateBlockRegex = /```jarble_delegate\s*\n([\s\S]*?)```/g;
  let dm: RegExpExecArray | null;
  while ((dm = delegateBlockRegex.exec(text)) !== null) {
    try {
      const parsed = JSON.parse(dm[1].trim());
      if (
        parsed &&
        typeof parsed === "object" &&
        parsed.to &&
        typeof parsed.to === "string" &&
        parsed.task &&
        typeof parsed.task === "string"
      ) {
        // Strip any accidental "delegate_to_" prefix the LLM may add by
        // mistake (the spec says "to" should be the bare slug).
        const slug = parsed.to.replace(/^delegate_to_/, "");
        calls.push({
          toolName: `delegate_to_${slug}`,
          task: parsed.task,
          context:
            typeof parsed.context === "string" && parsed.context.length > 0
              ? parsed.context
              : undefined,
        });
      }
    } catch {
      // Not valid JSON in the jarble_delegate block — skip silently.
      // The skipReason heuristic in flowChat.ts will surface the failure.
    }
  }

  // ── DEPRECATED: legacy delegation format, will be removed in a follow-up PR ──
  // Backward compat for bots still on the old soul.md prompt that says to
  // emit ```json { "tool": "delegate_to_..." }```. New prompt no longer
  // teaches this format. Remove once all running pods have re-synced.
  const jsonBlockRegex = /```json\s*\n([\s\S]*?)```/g;
  let lm: RegExpExecArray | null;
  while ((lm = jsonBlockRegex.exec(text)) !== null) {
    try {
      const parsed = JSON.parse(lm[1].trim());
      if (
        parsed &&
        typeof parsed === "object" &&
        parsed.tool &&
        typeof parsed.tool === "string" &&
        parsed.tool.startsWith("delegate_to_") &&
        parsed.task &&
        typeof parsed.task === "string"
      ) {
        calls.push({
          toolName: parsed.tool,
          task: parsed.task,
          context:
            typeof parsed.context === "string" && parsed.context.length > 0
              ? parsed.context
              : undefined,
        });
      }
    } catch {
      // Not valid JSON or not a delegation call - skip
    }
  }

  // De-dupe by (toolName, task) so a bot that emits BOTH a jarble_delegate
  // block AND the legacy json block for the same delegation only triggers once.
  const seen = new Set<string>();
  const deduped: ParsedDelegationCall[] = [];
  for (const c of calls) {
    const key = `${c.toolName}::${c.task}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(c);
  }

  return deduped;
}

// ── Flow-context loader (for recursive delegation) ──────────────────────────

/**
 * Look up a deployment's flow-membership context so we can rebuild its
 * own `DelegationTool[]` for recursive sub-delegation.
 *
 * Prefers the `flowIdHint` branch when supplied — a deployment may belong to
 * multiple flows, and during a recursive call we want to stay within the same
 * flow as the parent hop.
 *
 * **Ownership check:** when `userId` is supplied (the recommended path), the
 * `orchestrationFlows` lookup is filtered by that user's ownership (or org
 * membership). This prevents a recursive delegation chain from crossing into
 * a foreign user's flow definition. Without this guard, a deployment that
 * happens to be a member of multiple flows could leak the topology of a flow
 * the requester does not own — see the code review on JAR-fractal for the
 * full attack scenario.
 */
async function loadFlowContextForDeployment(
  deploymentId: string,
  flowIdHint?: string,
  userId?: string,
): Promise<
  | {
      flowId: string;
      node: FlowNode;
      nodes: FlowNode[];
      edges: FlowEdge[];
    }
  | null
> {
  try {
    const fdm = (tables as any).flowDeploymentMemberships;
    if (!fdm) return null;

    // Find a matching membership row
    let membership: { flowId: string; nodeId: string } | undefined;
    if (flowIdHint) {
      const rows = await db
        .select({ flowId: fdm.flowId, nodeId: fdm.nodeId })
        .from(fdm)
        .where(and(eq(fdm.deploymentId, deploymentId), eq(fdm.flowId, flowIdHint)))
        .limit(1);
      membership = rows[0];
    }
    if (!membership) {
      // Fallback: a deployment may be a member of multiple flows. If the
      // hint missed (or was unset), pick the first matching membership. We
      // still apply the owner-scoped flow check below, so an unauthorized
      // membership cannot be returned.
      const rows = await db
        .select({ flowId: fdm.flowId, nodeId: fdm.nodeId })
        .from(fdm)
        .where(eq(fdm.deploymentId, deploymentId))
        .limit(1);
      membership = rows[0];
      if (membership && flowIdHint) {
        log.warn(
          { deploymentId, flowIdHint, fallbackFlowId: membership.flowId },
          "loadFlowContextForDeployment fell back to non-hinted flow membership",
        );
      }
    }
    if (!membership) return null;

    // ── Owner-scoped flow lookup ────────────────────────────────────────
    // If the caller provided a userId, only return flows the user owns
    // (directly or via an org). This prevents IDOR through the recursive
    // delegation tree.
    let flowWhere = eq(tables.orchestrationFlows.id, membership.flowId);
    if (userId) {
      const memberships = await db.query.orgMembers.findMany({
        where: eq(tables.orgMembers.userId, userId),
        columns: { orgId: true },
      });
      const orgIds = memberships.map((m: any) => m.orgId);
      // Flows are scoped per-user (not per-org) in the current schema, so
      // we filter by `userId` directly. Org-scoped flows would need a
      // separate orgId column on `orchestrationFlows`; until that exists,
      // a user's ownership of the flow is the only valid check.
      void orgIds; // reserved for future org-scoped flow support
      flowWhere = and(
        eq(tables.orchestrationFlows.id, membership.flowId),
        eq(tables.orchestrationFlows.userId, userId),
      ) as any;
    }

    const flowRows = await db
      .select({
        id: tables.orchestrationFlows.id,
        definition: tables.orchestrationFlows.definition,
      })
      .from(tables.orchestrationFlows)
      .where(flowWhere)
      .limit(1);
    if (flowRows.length === 0) {
      if (userId) {
        log.warn(
          { deploymentId, flowId: membership.flowId, userId },
          "loadFlowContextForDeployment refused flow not owned by user",
        );
      }
      return null;
    }

    const def =
      typeof flowRows[0].definition === "string"
        ? JSON.parse(flowRows[0].definition)
        : (flowRows[0].definition as any);
    if (!def?.nodes || !def?.edges) return null;

    const node = def.nodes.find((n: FlowNode) => n.id === membership!.nodeId);
    if (!node) return null;

    return {
      flowId: flowRows[0].id as string,
      node,
      nodes: def.nodes as FlowNode[],
      edges: def.edges as FlowEdge[],
    };
  } catch (err) {
    log.debug(
      { deploymentId, err: err instanceof Error ? err.message : String(err) },
      "loadFlowContextForDeployment failed",
    );
    return null;
  }
}

/**
 * Strip `jarble_delegate` (and legacy `json` delegate) fenced blocks from a
 * bot's response text before it is surfaced to the parent synthesiser.
 *
 * Kept in sync with the two parser formats in `parseDelegationCalls()`.
 */
export function stripDelegationBlocks(text: string): string {
  return text
    .replace(/```jarble_delegate\s*\n[\s\S]*?```/g, "")
    .replace(
      /```json\s*\n\s*\{[^}]*"tool"\s*:\s*"delegate_to_[^}]*\}\s*```/g,
      "",
    )
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// ── Execute delegation ───────────────────────────────────────────────────────

/**
 * Execute a delegation - send a task to a target deployment and get the response.
 *
 * Uses the same chat pathway as tamboAgent (exec into pod via K8s API).
 * This is the non-streaming variant: the delegation completes and the full
 * response text is returned.
 *
 * **N-level recursion (JAR-fractal).** After the target's response lands, the
 * function re-parses it with `parseDelegationCalls()`. If the child emitted
 * its own `jarble_delegate` blocks AND the depth budget allows, it recursively
 * invokes `executeDelegation` for each nested hop, threading `parentCallId`
 * and `ancestorDeploymentIds` so:
 *
 *   - Every `agent_calls` row is chained via `parent_call_id` into a tree
 *   - Cycles (A → B → A) are rejected before they hit a pod
 *   - `depth > MAX_DELEGATION_DEPTH` is rejected with a clear error
 *
 * Callers that predate this feature and pass no `parentCallId` /
 * `ancestorDeploymentIds` / `flowId` still work — the recursion path simply
 * no-ops (no child flow context → no sub-delegation).
 */
export async function executeDelegation(params: {
  targetDeploymentId: string;
  targetNodeId: string;
  task: string;
  context?: string;
  contextScope: "task" | "summary" | "full";
  conversationHistory?: Array<{ role: string; content: string }>;
  sessionId?: string;
  depth?: number;
  /** Source deployment ID - used to scope orchestration events to the right SSE stream */
  sourceDeploymentId?: string;
  /** Tool name for orchestration event (e.g. "delegate_to_cto") */
  toolName?: string;
  /** User ID for ownership verification — prevents IDOR on delegation targets */
  userId?: string;
  /**
   * Parent agent_calls.id. `null` / `undefined` means this delegation is the
   * root of the chain (e.g. entry bot → first specialist). Recursive calls
   * inside `executeDelegation` will set this to the current row's id so the
   * tree can be reconstructed later.
   */
  parentCallId?: string | null;
  /**
   * Deployment IDs already in the call chain above this hop. Used for cycle
   * detection: if `targetDeploymentId` is in this list we throw
   * DelegationCycleError without hitting the pod.
   */
  ancestorDeploymentIds?: string[];
  /**
   * Flow ID the delegation is executing inside. Needed for sub-delegation
   * resolution (a deployment may belong to multiple flows; we stay in the
   * current one for the whole chain).
   */
  flowId?: string;
  /**
   * JAR-50: Parent OTel span id (for the observability span tree). Usually
   * the parent agent_calls row's span_id. Threaded through but not yet
   * required by the inline writer — Phase 2 (OTel SDK) will consume it.
   */
  parentSpanId?: string | null;
  /**
   * JAR-50: Trace id for the root chat turn. Stays constant through every
   * recursive delegation hop so the whole tree stitches into one trace.
   */
  traceId?: string | null;
  /** JAR-50: Org scope for audit rollups. */
  orgId?: string | null;
}): Promise<DelegationResult> {
  const depth = params.depth ?? 0;
  if (depth > MAX_DELEGATION_DEPTH) {
    throw new DelegationDepthExceededError(depth);
  }

  // ── Cycle detection ─────────────────────────────────────────────────────
  const ancestors = params.ancestorDeploymentIds ?? [];
  if (ancestors.includes(params.targetDeploymentId)) {
    throw new DelegationCycleError(ancestors, params.targetDeploymentId);
  }

  const startTime = Date.now();

  // Look up the target deployment with ownership verification
  // (check both personal ownership and org membership)
  let whereConditions;
  if (params.userId) {
    const memberships = await db.query.orgMembers.findMany({
      where: eq(tables.orgMembers.userId, params.userId),
      columns: { orgId: true },
    });
    const orgIds = memberships.map((m: any) => m.orgId);

    const ownershipFilter = orgIds.length > 0
      ? or(eq(tables.deployments.userId, params.userId), inArray(tables.deployments.orgId, orgIds))
      : eq(tables.deployments.userId, params.userId);

    whereConditions = and(eq(tables.deployments.id, params.targetDeploymentId), ownershipFilter);
  } else {
    whereConditions = eq(tables.deployments.id, params.targetDeploymentId);
  }

  const deployment = await db.query.deployments.findFirst({
    where: whereConditions,
  });

  if (!deployment) {
    throw new Error(`Delegation target not found: ${params.targetDeploymentId}`);
  }

  if (deployment.status !== "running") {
    throw new Error(
      `Delegation target "${deployment.name}" is not running (status: ${deployment.status})`,
    );
  }

  // Build the message based on context scope
  let message = params.task;
  if (params.contextScope === "summary" && params.context) {
    message = `Context: ${params.context}\n\nTask: ${params.task}`;
  } else if (params.contextScope === "full" && params.conversationHistory) {
    const history = params.conversationHistory
      .slice(-20) // Cap history to avoid massive payloads
      .map((m) => `${m.role}: ${m.content}`)
      .join("\n");
    message = `Conversation so far:\n${history}\n\nTask: ${params.task}`;
  }

  // Find the pod for this deployment and exec into it
  const { chatViaExec } = await import("./openclawGateway.js");
  const { findPodForDeployment } = await import("../k8s/index.js");

  const podName = await findPodForDeployment(params.targetDeploymentId);
  if (!podName) {
    throw new Error(
      `No running pod found for deployment "${deployment.name}" (${params.targetDeploymentId})`,
    );
  }

  const sessionId =
    params.sessionId || `flow-delegation-${params.targetDeploymentId}-${Date.now()}`;

  log.info(
    {
      targetDeploymentId: params.targetDeploymentId,
      targetNodeId: params.targetNodeId,
      depth,
      messageLen: message.length,
    },
    "Executing delegation",
  );

  // ── Insert agent_calls row (pending) via the JAR-50 writer helper ───────
  // The row is the anchor point for the delegation tree: recursive sub-calls
  // use this row's id as their `parent_call_id`. Insert BEFORE chatViaExec so
  // child calls emitted by the target can chain against it immediately.
  //
  // Using `agentCallsWriter` (instead of an inline `db.insert`) so every
  // delegation row gets the full OTel-ready column set populated:
  // span_name, span_kind, service_name, pod_name, user_id, org_id,
  // session_id, start_ms, end_ms, duration_ms, status_code, attributes.
  // This was the JAR-50 follow-up flagged after the live verification of
  // PR #56 — delegation rows in prod were landing with span_name/start_ms/
  // duration_ms = null because the inline writer didn't set them.
  //
  // The writer is fire-and-forget: it logs warnings on DB failure and
  // never throws, so an audit-store outage cannot break the delegation
  // path.
  const { startAgentCall, finishAgentCall } = await import("./agentCallsWriter.js");
  const agentCallHandle = await startAgentCall({
    kind: "delegation",
    skillName: params.toolName || `delegate_to_${params.targetNodeId}`,
    callerDeploymentId: params.sourceDeploymentId || null,
    calleeDeploymentId: params.targetDeploymentId,
    parentCallId: params.parentCallId ?? null,
    parentSpanId: params.parentSpanId ?? null,
    traceId: params.traceId ?? null,
    depth,
    userId: params.userId ?? null,
    orgId: params.orgId ?? null,
    sessionId,
    podName,
    spanName: "jarble.delegation.hop",
    requestBody: { task: params.task, contextScope: params.contextScope },
    attributes: {
      targetNodeId: params.targetNodeId,
      targetDeploymentId: params.targetDeploymentId,
      contextScope: params.contextScope,
      messageLen: message.length,
    },
  });
  // Pull the call id back out so the existing recursion threading
  // (`parentCallId: callId` at the sub-delegation site) keeps working
  // unchanged. The writer also generates a stable trace_id we propagate
  // to children.
  const callId = agentCallHandle.callId;
  const stepId = callId; // unify SSE stepId with agent_calls.id so SSE tree == DB tree

  // ── Emit orchestration:step:start event ──────────────────────────────────
  const orchestrationDeploymentId = params.sourceDeploymentId || params.targetDeploymentId;
  const orchestrationToolName = params.toolName || `delegate_to_${params.targetNodeId}`;

  try {
    emitOrchestrationStart({
      deploymentId: orchestrationDeploymentId,
      stepId,
      agentType: "delegation",
      agentName: deployment.name || params.targetNodeId,
      toolName: orchestrationToolName,
      task: params.task.slice(0, 200),
      targetDeploymentId: params.targetDeploymentId,
      parentStepId: params.parentCallId ?? undefined,
      depth,
    });
  } catch {
    // Non-fatal - orchestration events are nice-to-have
  }

  // Create an AbortController with timeout
  const abortController = new AbortController();
  const timeout = setTimeout(
    () => abortController.abort(),
    DELEGATION_TIMEOUT_MS,
  );

  // (`updateAgentCallsRow` removed — finishAgentCall from the writer now
  // handles the patch + status_code + duration + end_ms in one place.)

  try {
    const result = await chatViaExec(
      podName,
      sessionId,
      message,
      undefined, // no onDelta for delegations (not streaming to user)
      undefined, // no canvas image
      abortController.signal,
    );

    const durationMs = Date.now() - startTime;

    log.info(
      {
        targetDeploymentId: params.targetDeploymentId,
        targetNodeId: params.targetNodeId,
        durationMs,
        responseLen: result.text.length,
        depth,
        callId,
      },
      "Delegation completed",
    );

    // ── Recursive sub-delegation ─────────────────────────────────────────
    // Re-parse the child's response for nested delegation calls. If the
    // child emitted `jarble_delegate` blocks of its own, resolve them via
    // flow_deployment_memberships, check depth/cycle budgets, and recurse.
    //
    // `rawText` is preferred over `text` to match the format `parseDelegationCalls`
    // expects and to mirror what flowChat.ts does at the top level.
    const rawChildText = result.rawText || result.text || "";
    const childCalls = parseDelegationCalls(rawChildText);

    let finalResponse = result.text || "";
    let aggregatedUiBlocks: any[] = result.uiBlocks?.length ? [...result.uiBlocks] : [];
    let aggregatedComponentDefs: any[] = result.componentDefs?.length
      ? [...result.componentDefs]
      : [];
    let aggregatedSuggestions: string[] = result.suggestions?.length
      ? [...result.suggestions]
      : [];
    const childResults: DelegationResult[] = [];

    if (childCalls.length > 0) {
      // Strip the child's delegation blocks from the visible text so the
      // parent synthesiser doesn't see raw fences.
      const cleanedChildText = stripDelegationBlocks(result.text || "");

      // Resolve the child's own flow context so we can look up its tools.
      // We thread `params.userId` so the flow ownership check rejects any
      // membership that would cross into a foreign user's flow definition.
      const childFlowCtx = await loadFlowContextForDeployment(
        params.targetDeploymentId,
        params.flowId,
        params.userId,
      );

      if (!childFlowCtx) {
        log.debug(
          {
            targetDeploymentId: params.targetDeploymentId,
            childCallCount: childCalls.length,
          },
          "Child emitted delegation blocks but has no flow-membership context — ignoring (backward-compat path)",
        );
        finalResponse = cleanedChildText;
      } else {
        const childTools = buildDelegationTools(
          childFlowCtx.node,
          childFlowCtx.nodes,
          childFlowCtx.edges,
        );

        const errorAnnotations: string[] = [];
        const successAnnotations: string[] = [];

        for (const call of childCalls) {
          // Match the call against the child's available tools. Unknown
          // tools are skipped quietly — matches the top-level behavior in
          // flowChat.ts.
          const tool = childTools.find((t) => t.name === call.toolName);
          if (!tool) {
            log.debug(
              {
                parentCallId: callId,
                childDeployment: params.targetDeploymentId,
                toolName: call.toolName,
              },
              "Sub-delegation tool not found on child",
            );
            continue;
          }

          const nextAncestors = [...ancestors, params.targetDeploymentId];

          // Pre-check cycle + depth before even attempting the recursive
          // call. Surfacing these inline in the parent response is more
          // helpful than letting them throw back up.
          if (nextAncestors.includes(tool.targetDeploymentId)) {
            const msg = `[sub-delegation to ${call.toolName} refused: cycle back to ancestor ${tool.targetDeploymentId}]`;
            log.warn(
              { callId, chain: nextAncestors, target: tool.targetDeploymentId },
              "Sub-delegation cycle refused",
            );
            errorAnnotations.push(msg);
            continue;
          }
          if (depth + 1 > MAX_DELEGATION_DEPTH) {
            const msg = `[sub-delegation to ${call.toolName} refused: depth ${depth + 1} > max ${MAX_DELEGATION_DEPTH}]`;
            log.warn(
              { callId, attemptedDepth: depth + 1, max: MAX_DELEGATION_DEPTH },
              "Sub-delegation depth limit refused",
            );
            errorAnnotations.push(msg);
            continue;
          }

          try {
            const childResult = await executeDelegation({
              targetDeploymentId: tool.targetDeploymentId,
              targetNodeId: tool.targetNodeId,
              task: call.task,
              context: call.context,
              contextScope: tool.contextScope,
              conversationHistory: params.conversationHistory,
              sessionId: `flow-delegation-${tool.targetDeploymentId}-${Date.now()}-${nanoid(4)}`,
              depth: depth + 1,
              sourceDeploymentId: params.targetDeploymentId,
              toolName: call.toolName,
              userId: params.userId,
              parentCallId: callId,
              ancestorDeploymentIds: nextAncestors,
              flowId: childFlowCtx.flowId,
            });

            childResults.push(childResult);

            const childNode = childFlowCtx.nodes.find(
              (n) => n.id === tool.targetNodeId,
            );
            const roleLabel =
              childNode?.role || childNode?.label || tool.targetNodeId;
            successAnnotations.push(
              `**${roleLabel}:** ${childResult.response}`.trim(),
            );

            if (childResult.uiBlocks?.length) {
              aggregatedUiBlocks = aggregatedUiBlocks.concat(childResult.uiBlocks);
            }
            if (childResult.componentDefs?.length) {
              aggregatedComponentDefs = aggregatedComponentDefs.concat(
                childResult.componentDefs,
              );
            }
            if (childResult.suggestions?.length) {
              aggregatedSuggestions = aggregatedSuggestions.concat(
                childResult.suggestions,
              );
            }
          } catch (subErr) {
            const msg = `[sub-delegation to ${call.toolName} failed: ${
              subErr instanceof Error ? subErr.message : String(subErr)
            }]`;
            log.warn(
              {
                callId,
                toolName: call.toolName,
                err: subErr instanceof Error ? subErr.message : String(subErr),
              },
              "Sub-delegation errored",
            );
            errorAnnotations.push(msg);
          }
        }

        // Merge child outputs into the parent's visible response text. The
        // parent's own prose (minus delegation fences) comes first, then
        // each specialist's labeled reply, then any refusal annotations.
        const parts: string[] = [];
        if (cleanedChildText) parts.push(cleanedChildText);
        if (successAnnotations.length > 0) parts.push(successAnnotations.join("\n\n"));
        if (errorAnnotations.length > 0) parts.push(errorAnnotations.join("\n"));
        finalResponse = parts.join("\n\n").trim() || cleanedChildText;
      }
    }

    // ── Emit orchestration:step:end event ──────────────────────────────────
    try {
      emitOrchestrationEnd({
        deploymentId: orchestrationDeploymentId,
        stepId,
        agentType: "delegation",
        agentName: deployment.name || params.targetNodeId,
        toolName: orchestrationToolName,
        targetDeploymentId: params.targetDeploymentId,
        success: true,
        durationMs,
        resultPreview: (finalResponse || "").slice(0, 200),
        parentStepId: params.parentCallId ?? undefined,
        depth,
      });
    } catch {
      // Non-fatal
    }

    await finishAgentCall({
      call: agentCallHandle,
      status: "completed",
      responseBody: finalResponse || "",
      creditsCharged: 1,
      attributes: {
        responseLen: (finalResponse || "").length,
        childCount: childResults.length,
        uiBlocks: aggregatedUiBlocks.length,
        componentDefs: aggregatedComponentDefs.length,
      },
    });

    return {
      response: finalResponse,
      creditsUsed: 1, // 1 credit per delegation call (children add their own)
      durationMs,
      targetNodeId: params.targetNodeId,
      targetDeploymentId: params.targetDeploymentId,
      uiBlocks: aggregatedUiBlocks.length ? aggregatedUiBlocks : undefined,
      componentDefs: aggregatedComponentDefs.length ? aggregatedComponentDefs : undefined,
      suggestions: aggregatedSuggestions.length ? aggregatedSuggestions : undefined,
      callId,
      depth,
      children: childResults.length ? childResults : undefined,
    };
  } catch (err) {
    const durationMs = Date.now() - startTime;
    // ── Emit orchestration:step:end with failure ───────────────────────────
    try {
      emitOrchestrationEnd({
        deploymentId: orchestrationDeploymentId,
        stepId,
        agentType: "delegation",
        agentName: deployment.name || params.targetNodeId,
        toolName: orchestrationToolName,
        targetDeploymentId: params.targetDeploymentId,
        success: false,
        durationMs,
        error: err instanceof Error ? err.message : String(err),
        parentStepId: params.parentCallId ?? undefined,
        depth,
      });
    } catch {
      // Non-fatal
    }
    await finishAgentCall({
      call: agentCallHandle,
      status: "failed",
      errorMessage: (err instanceof Error ? err.message : String(err)).slice(0, 2000),
      attributes: { errorKind: err instanceof Error ? err.name : "unknown" },
    });
    throw err;
  } finally {
    clearTimeout(timeout);
  }
}
