import { execSync } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import type { OrchestratorState, PRResult } from "./types.js";
import type { Logger } from "./logger.js";
import { Monitor } from "./monitor.js";

export class GitHubIntegration {
  private repoRoot: string;
  private logger: Logger;

  constructor(repoRoot: string, logger: Logger) {
    this.repoRoot = repoRoot;
    this.logger = logger;
  }

  /** Check if gh CLI is available */
  isAvailable(): boolean {
    try {
      execSync("gh --version", { cwd: this.repoRoot, stdio: "pipe" });
      return true;
    } catch {
      return false;
    }
  }

  /** Create a PR from the current branch */
  async createPR(
    state: OrchestratorState,
    baseBranch: string,
    title?: string,
  ): Promise<PRResult> {
    const done = state.tasks.filter((t) => t.status === "done").length;
    const prTitle =
      title ??
      `jarble-dev: ${state.runId} — ${done}/${state.tasks.length} tasks`;

    const body = this.generatePRBody(state);

    const tmpPath = path.join(os.tmpdir(), `jarble-dev-pr-${state.runId}.md`);
    try {
      fs.writeFileSync(tmpPath, body, "utf-8");

      const output = execSync(
        `gh pr create --title "${prTitle}" --body-file "${tmpPath}" --base "${baseBranch}"`,
        { cwd: this.repoRoot, encoding: "utf-8", stdio: "pipe" },
      ).trim();

      const url = output;
      const number = parseInt(url.split("/").pop()!, 10);

      this.logger.info(`Created PR #${number}: ${url}`);

      return { url, number, title: prTitle };
    } finally {
      if (fs.existsSync(tmpPath)) {
        fs.unlinkSync(tmpPath);
      }
    }
  }

  /** Generate a detailed PR body from run state */
  generatePRBody(state: OrchestratorState): string {
    const totalCost = [...state.agents.values()].reduce(
      (s, a) => s + a.costUsd,
      0,
    );
    const totalDuration = state.completedAt
      ? Monitor.formatDuration(
          state.completedAt.getTime() - state.startedAt.getTime(),
        )
      : "in progress";
    const done = state.tasks.filter((t) => t.status === "done").length;
    const failed = state.tasks.filter((t) => t.status === "failed").length;

    const lines: string[] = [];

    lines.push("## Summary");
    lines.push("");
    lines.push(`- **Run ID:** \`${state.runId}\``);
    lines.push(
      `- **Tasks:** ${done}/${state.tasks.length} completed (${failed} failed)`,
    );
    lines.push(`- **Duration:** ${totalDuration}`);
    lines.push(`- **Total Cost:** $${totalCost.toFixed(2)}`);
    lines.push("");

    // Tasks table
    lines.push("## Tasks");
    lines.push("");
    lines.push("| Task | Status | Duration | Cost |");
    lines.push("|------|--------|----------|------|");
    for (const task of state.tasks) {
      const duration =
        task.startedAt && task.completedAt
          ? Monitor.formatDuration(
              task.completedAt.getTime() - task.startedAt.getTime(),
            )
          : "-";
      const agent = task.agentId ? state.agents.get(task.agentId) : undefined;
      const cost = agent ? `$${agent.costUsd.toFixed(2)}` : "-";
      lines.push(`| ${task.name} | ${task.status} | ${duration} | ${cost} |`);
    }
    lines.push("");

    // Quality Gates
    if (state.qualityReports.length > 0) {
      lines.push("## Quality Gates");
      lines.push("");
      lines.push("| Task | Typecheck | Tests |");
      lines.push("|------|-----------|-------|");
      for (const report of state.qualityReports) {
        const tc = report.typecheckPassed
          ? "pass"
          : `fail (${report.typecheckErrors?.length || 0} errors)`;
        const tests = report.testsPassed
          ? "pass"
          : `fail (${report.testFailures?.length || 0} failures)`;
        const task = state.tasks.find(t => t.id === report.taskId);
        lines.push(`| ${task?.name || report.taskId} | ${tc} | ${tests} |`);
      }
      lines.push("");
    }

    // Merge Results
    if (state.mergeResults.length > 0) {
      lines.push("## Merge Results");
      lines.push("");
      lines.push("| Branch | Status |");
      lines.push("|--------|--------|");
      for (const result of state.mergeResults) {
        const status =
          result.status === "conflict"
            ? `conflict: ${result.error ?? "unknown"}`
            : result.status;
        lines.push(`| ${result.branch} | ${status} |`);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("Generated by jarble-dev v0.3.0");

    return lines.join("\n");
  }

  /** Get the current branch name */
  getCurrentBranch(): string {
    return execSync("git rev-parse --abbrev-ref HEAD", {
      cwd: this.repoRoot,
      encoding: "utf-8",
    }).trim();
  }

  /** Push the current branch to origin */
  pushBranch(): void {
    const branch = this.getCurrentBranch();
    execSync(`git push -u origin "${branch}"`, {
      cwd: this.repoRoot,
      stdio: "pipe",
    });
    this.logger.info(`Pushed branch ${branch} to origin`);
  }
}
