# ─── Dedicated Server Setup Script (Kata / MicroVM) ─────────────────────────
#
# Hetzner dedicated servers use the Robot API, which is NOT managed by the
# hcloud Terraform provider. Instead, we generate a setup script that can be
# run manually on the dedicated server after provisioning it through the
# Hetzner Robot console or API.
#
# Workflow:
#   1. Order a dedicated server (e.g., AX42) via Hetzner Robot
#   2. Install Ubuntu 22.04 via the Robot installimage
#   3. Copy the generated script to the server
#   4. Run: bash /root/jarble-dedicated-setup.sh
#   5. Verify: kubectl get nodes (should show the dedicated node with kata label)
#
# ─────────────────────────────────────────────────────────────────────────────

variable "enable_dedicated_server" {
  description = "Generate setup script for a Hetzner dedicated server (Kata/MicroVM isolation)"
  type        = bool
  default     = false
}

variable "dedicated_server_type" {
  description = "Hetzner dedicated server model (for documentation only — provisioned via Robot)"
  type        = string
  default     = "AX42" # AMD EPYC, 64GB RAM, 2x512GB NVMe
}

# ─── Generated Setup Script ────────────────────────────────────────────────
#
# Renders a shell script with cluster-specific values (K3s token, master IP)
# baked in. The script:
#   1. Verifies /dev/kvm is present (bare-metal requirement)
#   2. Installs containerd + K3s agent
#   3. Installs Kata Containers + Cloud Hypervisor
#   4. Labels the node for kata scheduling
#   5. Joins the K3s cluster

resource "local_file" "dedicated_setup_script" {
  count    = var.enable_dedicated_server ? 1 : 0
  filename = "${path.module}/../scripts/generated/dedicated-setup.sh"

  content = <<-SCRIPT
    #!/bin/bash
    # ═══════════════════════════════════════════════════════════════════════════
    # Jarble Dedicated Server Setup — Kata + Cloud Hypervisor
    #
    # Generated by Terraform. Do not edit manually.
    #
    # Server type: ${var.dedicated_server_type}
    # Master IP:   ${hcloud_server.master.ipv4_address}
    # K3s version: ${var.k3s_version}
    #
    # Prerequisites:
    #   - Ubuntu 22.04 installed via Hetzner Robot installimage
    #   - /dev/kvm available (bare-metal only — no VPS)
    #   - Network connectivity to master at ${hcloud_server.master.ipv4_address}:6443
    #
    # Usage: bash dedicated-setup.sh
    # ═══════════════════════════════════════════════════════════════════════════
    set -euo pipefail

    echo "=== Jarble Dedicated Server Setup ==="
    echo "Target cluster master: ${hcloud_server.master.ipv4_address}"

    # ─── Verify KVM ──────────────────────────────────────────────────────────
    if [ ! -c /dev/kvm ]; then
      echo "ERROR: /dev/kvm not found."
      echo "Kata Containers requires bare-metal hardware with KVM support."
      echo "This script cannot run on a VPS."
      exit 1
    fi
    echo "✓ /dev/kvm available"

    # ─── System Packages ─────────────────────────────────────────────────────
    apt-get update -qq
    apt-get install -y -qq \
      open-iscsi nfs-common curl gnupg2 \
      apt-transport-https ca-certificates \
      software-properties-common

    systemctl enable iscsid
    systemctl start iscsid

    # ─── Install K3s Agent ───────────────────────────────────────────────────
    echo "Installing K3s agent ${var.k3s_version}..."
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_VERSION="${var.k3s_version}" sh -s - agent \
      --server "https://${hcloud_server.master.ipv4_address}:6443" \
      --token "${local.k3s_token}" \
      --node-label "jarble.ai/runtime-capable=kata" \
      --node-label "jarble.ai/server-type=dedicated"

    echo "✓ K3s agent installed and joined cluster"

    # ─── Install Kata Containers ─────────────────────────────────────────────
    echo "Installing Kata Containers..."

    # Add Kata repository
    KATA_VERSION="3.2.0"
    ARCH=$(uname -m)

    curl -fsSL https://github.com/kata-containers/kata-containers/releases/download/$KATA_VERSION/kata-static-$KATA_VERSION-$ARCH.tar.xz \
      -o /tmp/kata-static.tar.xz
    tar xf /tmp/kata-static.tar.xz -C /
    rm /tmp/kata-static.tar.xz

    # Symlink kata binaries
    ln -sf /opt/kata/bin/kata-runtime /usr/local/bin/kata-runtime
    ln -sf /opt/kata/bin/containerd-shim-kata-v2 /usr/local/bin/containerd-shim-kata-v2

    echo "✓ Kata Containers $KATA_VERSION installed"

    # ─── Install Cloud Hypervisor ────────────────────────────────────────────
    echo "Installing Cloud Hypervisor..."

    CLH_VERSION="v39.0"
    curl -fsSL "https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/$CLH_VERSION/cloud-hypervisor-static" \
      -o /opt/kata/bin/cloud-hypervisor
    chmod +x /opt/kata/bin/cloud-hypervisor

    echo "✓ Cloud Hypervisor $CLH_VERSION installed"

    # ─── Configure containerd for Kata ───────────────────────────────────────
    echo "Configuring containerd for kata-clh handler..."

    CONTAINERD_CONFIG="/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
    mkdir -p "$(dirname "$CONTAINERD_CONFIG")"

    # Append kata-clh runtime handler to containerd config
    cat >> "$CONTAINERD_CONFIG" <<'CONTAINERD_EOF'

    # Kata Containers with Cloud Hypervisor
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh]
      runtime_type = "io.containerd.kata.v2"
      privileged_without_host_devices = true
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh.options]
        ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-clh.toml"
    CONTAINERD_EOF

    # Restart K3s to pick up containerd changes
    systemctl restart k3s-agent

    echo "✓ containerd configured with kata-clh handler"

    # ─── Verify ──────────────────────────────────────────────────────────────
    echo ""
    echo "=== Setup Complete ==="
    echo "Verify from the master node:"
    echo "  kubectl get nodes -l jarble.ai/runtime-capable=kata"
    echo "  kubectl get runtimeclass"
    echo ""
    echo "Test Kata isolation:"
    echo "  kubectl run kata-test --image=busybox --rm -it --restart=Never \\"
    echo "    --overrides='{\"spec\":{\"runtimeClassName\":\"kata-clh\"}}' -- uname -a"
  SCRIPT

  file_permission = "0755"
}
