/**
 * Bundles the local MCP stdio server into a single JS file.
 *
 * Output: `dist/jarble-local-server.js` — a Node 18+ script with a shebang,
 * suitable for dropping onto a deployment's PVC at /data/mcp/ (replacing
 * the legacy jarble-ui-server.js once tool migration is complete).
 *
 * Every tool module under `servers/local/tools/` is pulled in as an entry
 * point so its top-level `registerTool()` call executes at load time.
 */

import { build } from "esbuild";
import { mkdirSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

// Run via `tsx src/mcp/build.ts`, which supplies a CJS `__dirname`.
declare const __dirname: string;

const ROOT = resolve(__dirname, "..", "..");
const TOOLS_DIR = resolve(__dirname, "servers", "local", "tools");
const ENTRY = resolve(__dirname, "servers", "local", "index.ts");
const OUT_DIR = resolve(ROOT, "dist");
const OUT_FILE = resolve(OUT_DIR, "jarble-local-server.js");
const TMP_ENTRY = resolve(OUT_DIR, ".jarble-local-entry.ts");

function listToolFiles(): string[] {
  try {
    return readdirSync(TOOLS_DIR)
      .filter((f) => (f.endsWith(".ts") || f.endsWith(".js")) && !f.endsWith(".test.ts"))
      .filter((f) => {
        try {
          return statSync(join(TOOLS_DIR, f)).isFile();
        } catch {
          return false;
        }
      })
      .map((f) => join(TOOLS_DIR, f));
  } catch {
    return [];
  }
}

function writeEntry(toolFiles: string[]): void {
  mkdirSync(OUT_DIR, { recursive: true });
  const importLines = toolFiles
    .map((f) => `import "${f.replace(/\\/g, "/")}";`)
    .join("\n");
  const body = [
    "// AUTO-GENERATED by src/mcp/build.ts — do not edit.",
    `import "${ENTRY.replace(/\\/g, "/")}";`,
    importLines,
    "",
  ].join("\n");
  writeFileSync(TMP_ENTRY, body, "utf8");
}

async function main(): Promise<void> {
  const toolFiles = listToolFiles();
  writeEntry(toolFiles);

  await build({
    entryPoints: [TMP_ENTRY],
    bundle: true,
    platform: "node",
    target: "node18",
    format: "cjs",
    outfile: OUT_FILE,
    banner: { js: "#!/usr/bin/env node" },
    external: [
      // Node built-ins are handled automatically; anything that should stay
      // as `require()` at runtime goes here.
    ],
    legalComments: "none",
    minify: false,
    sourcemap: false,
    logLevel: "info",
  });

  // eslint-disable-next-line no-console
  console.log(
    `[build:local-mcp] wrote ${OUT_FILE} (${toolFiles.length} tool modules included)`,
  );
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("[build:local-mcp] failed:", err);
  process.exit(1);
});
